---
title: "Interests"
---

Over the course of development, we acquire the ability to conceptualize others’ thoughts and feelings as distinct from our own. This is part of what allows us to engage in meaningful social interactions where our understanding of another’s perspective directly shapes our use of language. 

I am interested in how we are able to efficiently and effortlessly integrate contextual information, account for differences in perspective, and tailor our speech to meet the needs of our communicative partner in real-time. What are the cognitive mechanisms regulating these computational processes and how do those mechanisms correspond to age-related differences in the way in which we refer to the world around us? Moreover, which factors determine why certain individuals maintain communicative efficacy throughout adulthood while others are more prone to linguistic decline, leading to critical communicative errors?

Through the use of experimental data, I attempt to answer these questions by analyzing the relationship between pragmatic abilities and cognitive functions across the lifespan. 